[module/launcher]
type = custom/text
content = ""
content-foreground = ${colors.blue}
click-left = ~/.config/polybar/scripts/exec rofi -show drun

[module/workspaces]
type = internal/xworkspaces
enable-click = true

; formatting
format = <label-state>
format-font = 2
label-active = "ﰉ   "
label-active-foreground = ${colors.blue}
label-occupied = "ﰉ   "
label-urgent = "ﰉ   "
label-urgent-foreground = ${colors.red}
label-empty = "ﰊ   "
label-empty-foreground = ${colors.lightblack}


[module/title]
type = internal/xwindow

format = <label>
format-background = ${colors.background}
format-foreground = ${colors.foreground}
format-padding = 4

label = %title%
label-maxlen = 50

label-empty = Empty
label-empty-foreground = #707880
