#!/usr/bin/env bash

CONF_PATH=$HOME/.config/openbox
SRC_PATH=$CONF_PATH/src

EWW_PATH=$SRC_PATH/eww
POLYBAR_PATH=$SRC_PATH/polybar

# compositor
picom --config=$CONF_PATH/picom.conf -b &

run_polybar () {
  $HOME/.config/polybar/launch.sh
}

run_eww () {
  eww -c $EWW_PATH daemon
  $EWW_PATH/scripts/redshift restore
}

xrdb merge $HOME/.Xresources
nitrogen --set-zoom-fill --random ~/wallpapers/

run_polybar
run_eww

# notification
dunst &

# network manager
nm-applet &


# Clipboard
copyq &

# volume
volumeicon &


